//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandyTest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandyTest.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandyTest.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string button_CreateNew {
            get {
                return ResourceManager.GetString("button_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✕.
        /// </summary>
        public static string button_functionalX {
            get {
                return ResourceManager.GetString("button_functionalX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Active.
        /// </summary>
        public static string button_MakeActive {
            get {
                return ResourceManager.GetString("button_MakeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create report.
        /// </summary>
        public static string imageButton_CreateReport {
            get {
                return ResourceManager.GetString("imageButton_CreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string imageButton_Log {
            get {
                return ResourceManager.GetString("imageButton_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual test.
        /// </summary>
        public static string imageButton_ManualTest {
            get {
                return ResourceManager.GetString("imageButton_ManualTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Issues.
        /// </summary>
        public static string imageButton_ViewIssues {
            get {
                return ResourceManager.GetString("imageButton_ViewIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project.
        /// </summary>
        public static string label_CreateProject {
            get {
                return ResourceManager.GetString("label_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select project.
        /// </summary>
        public static string label_SelectProject {
            get {
                return ResourceManager.GetString("label_SelectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string popUP_Cancel {
            get {
                return ResourceManager.GetString("popUP_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string popUP_Create {
            get {
                return ResourceManager.GetString("popUP_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string popUP_Description {
            get {
                return ResourceManager.GetString("popUP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        public static string popUP_EnterDesc {
            get {
                return ResourceManager.GetString("popUP_EnterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter project name.
        /// </summary>
        public static string popUP_EnterName {
            get {
                return ResourceManager.GetString("popUP_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string popUP_Name {
            get {
                return ResourceManager.GetString("popUP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects_label {
            get {
                return ResourceManager.GetString("Projects_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string repot_bug {
            get {
                return ResourceManager.GetString("repot_bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string tooltip_Delete {
            get {
                return ResourceManager.GetString("tooltip_Delete", resourceCulture);
            }
        }
    }
}
